### ISSUE TITLE
How is the data access race protection implemented?

### ISSUE THREAD

**Issue by adel-mamin** [MaJerle/stm32h7-dual-core-inter-cpu-async-communication#2]
Looking at the code it is not clear how do you make sure that M7 core is not reading inconsistent data from `rb_cm4_to_cm7` when M4 is in the middle of writing to it. Could you please clarify?

**Comment by MaJerle** [comment]
What exactly is unclear? If you take a look at ringbuffer implementation, you will notice that read operation only modified `r` member of buffer and write operation only modified `w` member of buffer structure.

Now, CM4 only writes data, CM7 only reads data. So there is no case where both cores would modify `r` or `w` at the same time. They can, of course, one modify `r` and second `w` at the same time, but they never modify same member at the same time since it is impossible to do it.

**Comment by adel-mamin** [comment]
Ok, I see. Thanks for the clarification!
I am closing the issue.
